### ISSUE TITLE
Correction on spray-json

### ISSUE THREAD

**Issue by ipsq** [lihaoyi/upickle#150]
From the [uPickle documentation](http://www.lihaoyi.com/upickle-pprint/upickle/#WhyuPickle): 
_... None of the libraries I could find were pure Scala: **spray-json** uses **parboiled1** which is written in Java..._

This is no longer the case as of [spray-json v1.3.0 (2014-09-22)](https://github.com/spray/spray-json/blob/4fbde3a833cb122c71aaf85a1b3bbd31e130cb62/CHANGELOG#L24)

Would it be possible to implement a version that uses spray-json instead of jawn?

**Comment by lihaoyi** [comment]
Bug bankruptcy
