### ISSUE TITLE
Error Failed to deserialize info of file compiled with Scala.js 0.6.8

### ISSUE THREAD

**Issue by sergeda** [lihaoyi/upickle#161]
I got this error when add upickle to my project and try to use it:

> [error](js/compile:scalaJSIR) org.scalajs.core.ir.IRVersionNotSupportedException: Failed to deserialize info of file compiled with Scala.js 0.6.8 (supported: 0.6.0, 0.6.3, 0.6.4, 0.6.6, 0.6.5): /Users/sergey/.ivy2/cache/com.lihaoyi/upickle_sjs0.6_2.11/jars/upickle_sjs0.6_2.11-0.4.1.jar:upickle/Js$False$.sjsir

**Comment by LogicalTime** [comment]
I am getting this error as well. Any advice? I am trying to update my scalajs-sbt plugin, but I am unable to just yet.

**Comment by aborsu** [comment]
Can you paste your dependencies in your sbt build?

**Comment by lihaoyi** [comment]
Bug bankruptcy
