### ISSUE TITLE
read attempt only works on second attempt in safari

### ISSUE THREAD

**Issue by josephhajduk** [lihaoyi/upickle#165]
Hello,  

Getting the following error when I attempt to read a somewhat large json string.

[Log] upickle.Invalid$Data: Array(n) (data: <function1>) (appweb-opt.js, line 2543)
[Log] received_search_query (baloneymeter.com, line 310)

There error is not consistent,  it seems to randomly pick an element to fail on.  I am using Safari Version 9.1 (11601.5.17.1),  it also happens in the current version iphone/ipad simulator

The second or third time I attempt to read similar data of similar size,  or even identical data,  it works without error.

I have a nasty workaround by cascading try/catches

See https://gist.github.com/josephhajduk/e5f31641b95c0ba8ec9d61e9502a885f for examples.

**Comment by lihaoyi** [comment]
Bug bankruptcy
