### ISSUE TITLE
Strange serialization of scala Map

### ISSUE THREAD

**Issue by l15k4** [lihaoyi/upickle#17]
Hey,

I tried to serialize this with upicke 0.2.2, scala 2.11.2, scala.js 0.5.3 : 

```
case class RequestMessage(requestId: String, op: String, processor: String, args: Map[String, String])
write(RequestMessage(
      "1d6d02bd-8e56-421d-9438-3bd6d0079ff1",
      "eval",
      "",
      Map(
        "gremlin" -> "g.v(x).out",
        "bindings" -> "",
        "language" -> "gremlin-groovy"
      )
    )
)

{"requestId":"1d6d02bd-8e56-421d-9438-3bd6d0079ff1","op":"eval","processor":"","args":[["gremlin","g.v(x).out"],["bindings",""],["language","gremlin-groovy"]]}
```

Do I need to implement unapply method for maps too in case classes? The map is serialized into some sort of list of arrays. Even if I serialize it directly it resolves to : 

`[["gremlin","g.v(x).out"],["bindings",""],["language","gremlin-groovy"]]`

**Comment by OndrejSpanel** [comment]
It seems the 

> Well, here's an idea: just shadow the `Map` reader/writer
> 
> ```scala
>   implicit def MapW[K: W, V: W] =  W[Map[K, V]](
>     x => Js.Arr(x.toSeq.map(writeJs[(K, V)]):_*)
>   )
>   implicit def MapR[K: R, V: R] = R[Map[K, V]](
>     validate("Array(n)"){case x: Js.Arr => x.value.map(readJs[(K, V)]).toMap}
>   )
> ```
> 
> with your own. Then you can serialize them however you want ^_^ No need for upickle to get involved at all!

It seems the library has evolved meanwhile and the writer needs to be written differently? On certainly needs to write `ujson` instead of deprecated `Js`, but some other changes seem to be necessary for this to compile.
