### ISSUE TITLE
Support new Google protocol buffers canonical json mapping

### ISSUE THREAD

**Issue by LogicalTime** [lihaoyi/upickle#173]
Google's new protobuf version supports canonical encoding in json.
https://developers.google.com/protocol-buffers/docs/proto3#json

Can we support that here or would we make it a separate project? I thought it would be really nice to have, upickle,  a json library that works with ScalaJs support ScalaPB.

Right now ScalaPB doesn't seems to have support from any libraries that work with scalaJs:
http://trueaccord.github.io/ScalaPB/json.html

**Comment by lihaoyi** [comment]
Bug bankruptcy
