### ISSUE TITLE
Feature request: use pprint with jdeserialize

### ISSUE THREAD

**Issue by dportabella** [lihaoyi/upickle#183]
let's say i have this:

```
import java.io._
case class Person(name: String)
val person = Person("john")
val oos = new ObjectOutputStream(new FileOutputStream("file.ser"))
oos.writeObject(person)
oos.close()
```

and one year later, I find the `file.ser` file, but I've lost the source code with the `Person` class definition.

I can use [jdeserialize](https://github.com/unsynchronized/jdeserialize) as follows:
```
$ java -jar jdeserialize.jar file.ser
read: application.Person _h0x7e0002 = r_0x7e0000;
//// BEGIN stream content output
application.Person _h0x7e0002 = r_0x7e0000;
//// END stream content output

//// BEGIN class declarations (excluding array classes)
class application.Person implements java.io.Serializable {
    java.lang.String name;
}

//// END class declarations

//// BEGIN instance dump
[instance 0x7e0002: 0x7e0000/application.Person
  field data:
    0x7e0000/application.Person:
        name: r0x7e0003: [String 0x7e0003: "john"]
]
//// END instance dump
```

It would be great if I could use pprint together with jdeserialize as follows:
```
@ val fis = new ObjectInputStream(new FileInputStream("file.ser"))
@ pprint.readObjectAndPprintln(fis)
case class Person(name: String)
val person = Person("john")
```

What do you think about this feature request?

However it seems that the jdeserialize project is not maintained any more. Do you know any alternative library?

**Comment by lihaoyi** [comment]
Integrating with an ancient unmaintained library is probably out of scope

**Comment by dportabella** [comment]
The feature request can be rephrased as follows:
Feature request: use pprint on serialized files (integrating with jdeserialize, or any other similar updated library, or implementing it from scratch on pprint)
