### ISSUE TITLE
Error message when trying to serialize object of type Any

### ISSUE THREAD

**Issue by mb720** [lihaoyi/upickle#192]
Thanks a lot for your great library!

μPickle can't serialize case classes that have a field of type Any. So this won't fly:
`case class FileInfo (name: String, content: Any)`

It would be really nice if we could get a more informative error than this:

> [error] C:\Users\me\Dev\Scala\my\app\js\src\main\scala\client\Client.scala:50: type mismatch;
> [error]  found   : upickle.default.Writer[(shared.FileInfo, shared.FileInfo)]
> [error]  required: upickle.default.Aliases.W[(String, Any)]
> [error]     (which expands to)  upickle.default.Writer[(String, Any)]
> [error]       val eventualResponse = Ajaxer[MyApi].postFile(fileInfo).call()
> [error]                                                                                          ^

I'm thinking something along the lines of:

> case class FileInfo contains a field of type Any; μPickle can't serialize that

**Comment by lihaoyi** [comment]
Bug bankruptcy

**Comment by mb720** [comment]
Sorry to hear.

Stil, I had a great time using uPickle and for me it raised the bar of what I expect from web development.
