### ISSUE TITLE
Serialize to empty object {} in js/jvm project, while err "Key Missing:" in reading on the other side.

### ISSUE THREAD

**Issue by cuzfrog** [lihaoyi/upickle#203]
This is a serious bug:

case class definition:
```scala
private case
class ItemFormState(id: Long = -1,
                    sourceType: SourceType = SourceType.Original,
                    isSaving: Boolean = false,
                    values: Map[String, String] = {
                      //initial values
                      Map(
                        ID_DataFormat -> Constants.dataFormat.head,
                        ID_DataPeriod -> Constants.dataPeriod.head,
                        ID_ItemBassType -> Constants.itemBassTypeSet.head.toString
                      )
                    },
                    invalids: Map[String, String] = Map()
                   )
```

test:
```scala
val cs = ItemFormState()
          println(cs)
          println(write(cs))
```

result:
```
ItemFormState(-1,Original,false,Map(dataFormat -> Hit, dataPeriod -> Day, itemBassType -> Historical),Map())
{}  // well, this must be intentionally made to be empty.
```

**While, on the server, `read` complains cannot find `id`**

**Comment by cuzfrog** [comment]
Turns out this is caused by continuous compilation, in which there is a cache incongruity between macro-generated code and updated user code. sbt `clean` and recompilation solved above issue so far.

**Comment by cuzfrog** [comment]
```scala
import upickle.default._

sealed trait Message{
  def err:Seq[String]
}
object Message{
  def fromJSON(in:String):Message = read[Message](in)
  
  private implicit val readWriter: ReadWriter[Message] =
    macroRW[PhoneMessage] merge macroRW[PcMessage]
}

case class PhoneMessage(phone:String,err:Seq[String] = Seq()) 
  extends Message{
    def toJSON:String = write(this)
  }
case class PcMessage(pc:String,err:Seq[String] = Seq()) 
  extends Message{
    def toJSON:String = write(this)
  }
  

val msg = PcMessage("iMac").toJSON

println(Message.fromJSON(msg))
```

I tested above, which works fine on jvm. But "Key Missing" occurs when using remotely.

**Comment by torstenrudolf** [comment]
@cuzfrog can you elaborate what you mean with "when using remotely"?

I just ran into the same problem I think. when I test the reading/writing in the sbt console it works fine. but when it runs on the jvm it fails with the "key missing" message, even though the default parameters are specified.

**Comment by cuzfrog** [comment]
@torstenrudolf 

>what you mean with "when using remotely"?

js to jvm.

I reckon this problem arises when one of the conditions meets:
1. Inconsistency between macro-generated code and source code. When class signature changes, incremental compilation may fail to detect the change on one/both side(s) of jvm or js.
2. In a class hierarchy, serialization done by sub-classes is to be deserialized by super-class(see my example above). This may be `uPickle`'s deficiency.

Solutions:

1. Clean to make a full compilation. See sbt's doc about incremental compilation, where you may find hints on how to minimize this problem.
2. `read` or `write` class hierarchy in top class:

```scala
sealed trait Message{
  def err:Seq[String]

  def toJSON: String = write(this) //serialize this here.
}
object Message{
  def fromJSON(in:String):Message = read[Message](in)
  
  implicit val readWriter: ReadWriter[Message] =
    macroRW[PhoneMessage] merge macroRW[PcMessage] // when implicit val is public, it can be seen from trait.
}
```

I think i didn't see the problem anymore when applied these solutions/principles.

**Comment by torstenrudolf** [comment]
my problem persisted after `sbt clean`

in my case it failed with a very simple case class with no hierarchy:
```
case class X(a: Option[String] = None, b: Option[String] = None)

object X {
  def something...
}
```

When reading in "{}" it would fail with key missing error (even after full compilation). but after I changed the object's name it worked.

**Comment by lihaoyi** [comment]
Bug bankruptcy
