### ISSUE TITLE
akka-http-upickle tests broken after upgrade to 0.5.1

### ISSUE THREAD

**Issue by hseeberger** [lihaoyi/upickle#214]
After upgrading from 0.4.3 to 0.5.1 the following doesn't compile any more:
https://github.com/hseeberger/akka-http-json/blob/master/akka-http-upickle/src/test/scala/de/heikoseeberger/akkahttpupickle/UpickleSupportSpec.scala#L48

Could you please help?

**Comment by lihaoyi** [comment]
@hseeberger you now need to do

```scala
implicit val RequestEntityReadWrite = upickle.default.macroRW[RequestEntity}
```

somewhere in scope (with similar things for all the other case classes `RequestEntity` transitively depens on) for this to work. This can be in the case class's companion object, or somewhere else that you import the implicits from

**Comment by lihaoyi** [comment]
I set up a Gitter room, let's move any follow-on discussion there https://gitter.im/lihaoyi/upickle

**Comment by hseeberger** [comment]
Thanks!
