### ISSUE TITLE
 java.util.NoSuchElementException: key not found

### ISSUE THREAD

**Issue by rleibman** [lihaoyi/upickle#216]
Hey, hi! I'm working with 0.4.4, I don't have much time to update to the latest. I get the following error when doing compile:fastOptJs

`
[error] java.util.NoSuchElementException: key not found: 
derive$macro$48$lzycompute__p1__Lupickle_Types$Writer [error] at 
scala.collection.MapLike.default(MapLike.scala:232) [error] at 
scala.collection.MapLike.default$(MapLike.scala:231) [error] at 
scala.collection.AbstractMap.default(Map.scala:59) [error] at 
scala.collection.mutable.HashMap.apply(HashMap.scala:65)
`

Any ideas?

**Comment by lihaoyi** [comment]
0.4.4 is deprecated

**Comment by rleibman** [comment]
Man, that was ugly, I updated to your latest code and had to write tons of custom picklers for all my case classes! Well, at least I think I have a bit more control now. 
Thanks for keeping the project open!
