### ISSUE TITLE
support hocon syntax

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [lihaoyi/upickle#217]
motivation:
* readability of wire format
* compatibility with lightbend/config

please add support for hocon syntax flavor,
https://github.com/lightbend/config/blob/master/HOCON.md

specifically, both upickle reader and writer should support unquoted names and equals:
```
{ a : 1 }
{ a = 1 }
{ "a" = 1 }
{ "a" : 1 }
```

**Comment by lihaoyi** [comment]
I'm not going to do this, but in 0.6.0 you can probably do this yourself since uPickle can support [other AST formats](http://www.lihaoyi.com/upickle/#OtherASTs)
