### ISSUE TITLE
Mistake in the docs

### ISSUE THREAD

**Issue by ranchoiver** [lihaoyi/upickle#219]
https://github.com/lihaoyi/upickle/blob/48ae9dc1e5386a668a3f37118517b1c41698f994/upickleReadme/Readme.scalatex#L752-L753

> Another thing of note is the .web entries; these are benchmarking uPickle using the Node.js JSON.parse and JSON.stringify builtin functions, rather than our own parser. It turns out that these builtins appear to be slower than our parser for this benchmark, so **they're not the default**, but they're available as the **upickle.default.web.read**/write functions or the upickle.WebJson object if you for some reason want to use them.

Is this correct? Looks like a mistake, also the benchmark a little higher on the page suggests that **default** is faster.

Should be:

> available as the **upickle.legacy.web.read**/write functions

**Comment by lihaoyi** [comment]
@ranchoiver yeah that's obsolete; lemme fix it

**Comment by lihaoyi** [comment]
The double meaning of the word `default` is confusing; tried to tidy it up
