### ISSUE TITLE
how about , field exists method

### ISSUE THREAD

**Issue by rajeshpv** [lihaoyi/upickle#224]
This is not an issue, but thinking how about adding json("username").exists instead of throwing NoSuchElement. Or donno if json("username").strOpt will return Option[String], this can lead to numOpt etc.,

btw., thanks for adding json("isPresent").bool, I was using my own implicit method to acheive it.

**Comment by joshlemer** [comment]
@lihaoyi what was the resolution of this? WillNotFix or something else?

**Comment by tekumara** [comment]
Also keen to understand why this has been closed, and what the recommended approach to check for presence is?

**Comment by lihaoyi** [comment]
questions go in the gitter channel

**Comment by tekumara** [comment]
Will direct further questions there. For others who might end up here, one way to do this is `obj.value.contains("FieldName")` where obj is a `ujson.Obj`

**Comment by nicmcd** [comment]
@lihaoyi this topic should be added to the documentation. There is no discussion about how to ask the data structure whether a member exists or not.
