### ISSUE TITLE
Automatic Reader/Writer derivation for case classes

### ISSUE THREAD

**Issue by cornerman** [lihaoyi/upickle#229]
For a project, I need automatic derivation of upickle readers and writers for case classes (and potentially sealed traits).

In a naive approach, I tried to define them implicitly:
```scala
  implicit def serializeUpickle[T]: Reader[T] = macroR[T]
  implicit def deserializeUpickle[T]: Writer[T] = macroW[T]
```

But this yields a compile error for some types: `scala.ScalaReflectionException: type T is not a class`

Is there already a way to achieve this?

**Comment by lihaoyi** [comment]
Everything possible is described in http://www.lihaoyi.com/upickle/#Builtins

**Comment by nafg** [comment]
You can use Magnolia (https://github.com/propensive/magnolia)

**Comment by plokhotnyuk** [comment]
...  or https://github.com/propensive/scalaz-deriving

**Comment by nafg** [comment]
I haven't used either, and I didn't fully understand the readme, but it
sounds like that only does semi-auto which upickle already has?
