### ISSUE TITLE
Could not find implicit value for evidence parameter / Not enough arguments for method write

### ISSUE THREAD

**Issue by wiradikusuma** [lihaoyi/upickle#231]
This simple mixed-content Map fails during compilation:

	write(Map(
				"foo" -> "bar",
				"message" -> Map("hello" -> "world")
			))

With this error:

	Error:(21, 16) could not find implicit value for evidence parameter of type upickle.default.Writer[scala.collection.immutable.Map[String,Object]]
	Error occurred in an application involving default arguments.
			val x = write(Map(

	Error:(21, 16) not enough arguments for method write: (implicit evidence$4: upickle.default.Writer[scala.collection.immutable.Map[String,Object]])String.
	Unspecified value parameter evidence$4.
	Error occurred in an application involving default arguments.
			val x = write(Map(

**Comment by raquo** [comment]
upickle does not know how to serialize `Object`.

I think you'll need to give a more specific type to it, for example by creating a sealed trait with subtypes that wrap your String and Map[String, String], and then give upickle a Map[String, YourSealedTreait] instead of Map[String, Object].

**Comment by wiradikusuma** [comment]
Thank you, I've read about that in the doc, but my use case is actually to serialize arbitrary maps. Do you have recommendation for that?

**Comment by raquo** [comment]
I don't think what you're looking for is possible with upickle. upickle does not usually store type information in the serialized JSON string (except for sealed traits / enums). So when deserializing, you need to know which type you're deserializing into, and have a deserializer available for that type.

If this really is a requirement, try to find a library that encodes the types in serialized strings. I'm not sure which ones do that.

**Comment by lihaoyi** [comment]
You can also construct a Js.Value yourself out of Js.Objs if you want a
heterogenous JSON tree
