### ISSUE TITLE
Publish ujson-play for ScalaJS

### ISSUE THREAD

**Issue by asdcdow** [lihaoyi/upickle#233]
Recent versions of `play-json` support ScalaJS. So, it would be nice if I could use `ujson-play` for ScalaJS.

**Comment by lihaoyi** [comment]
I'm probably not going to bother cross publishing all of the integrations, but they're all just one file of not-a-lot-of-code so feel free to copy-paste them into your codebase

**Comment by asdcdow** [comment]
Ok, fair enough.
