### ISSUE TITLE
example from documentation does not work

### ISSUE THREAD

**Issue by DomingoExabeam** [lihaoyi/upickle#244]
I copied and paste this into a Scala worksheet:

val str = """[{"myFieldA":1,"myFieldB":"g"},{"myFieldA":2,"myFieldB":"k"}]"""
val json: ujson.Js = ujson.read(str)

json.arr.remove(1)
json(0)("myFieldA") = 1337
json(0)("myFieldB") = json(0)("myFieldB").str + "lols"

and I get 
Error:(18, 69) ')' expected but string literal found.
inst$A$A.`get$$instance_0$$json(0)("myFieldA")`; println("json(0)("myFieldA"): " + {val $$temp$$ = inst$A$A.json(0)("myFieldA") ; MacroPrinter.printDefInfo($$temp$$).replace("inst$A$A.", "") + " = " + ( print$$$Worksheet$$$Array$$$($$temp$$) ).stripPrefix("A$A40$A$A40$")})
                                                                   ^

Any suggestions?

**Comment by lihaoyi** [comment]
that is a problem with your worksheet, not uPickle. Feel free to open an issue with who-ever implemented your worksheets

**Comment by DomingoExabeam** [comment]
The worksheet is in IntelliJ, the most popular Scala IDE I believe.

You are correct. It works fine in regular projects outside the worksheet. 

Thanks!
