### ISSUE TITLE
Is Maven repo up-to-date?

### ISSUE THREAD

**Issue by gorros** [lihaoyi/upickle#248]
I can't find `isNull` method in 0.6.6 version to avoid this exception: ujson.Js$InvalidData: Expected Js.Str (data: null).

**Comment by gorros** [comment]
Also, how to do it in an idiomatic way with ujson?

**Comment by joostverdoorn** [comment]
👍 I'd also greatly appreciate a new release to be able to use `isNull`.

**Comment by lihaoyi** [comment]
tagged 0.6.7
