### ISSUE TITLE
Upickle 0.7.1 drops default values in Scala case class

### ISSUE THREAD

**Issue by Allan-Gong** [lihaoyi/upickle#251]
```
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.write

object Main extends App {

  val p = Person(age = 90)

  val json = write(p)

  println(json) // {"age":90}

}

case class Person(name: String = "Allan", age: Int)
object Person{
  implicit val rw: RW[Person] = macroRW
}
```

Name is not present in the converted JSON string ??

**Comment by lihaoyi** [comment]
this is expected and documented behavior

**Comment by Allan-Gong** [comment]
@lihaoyi 

Can you provide a link to the related documentation ? I can't seem to find it ...

**Comment by raquo** [comment]
@Allan-Gong 

http://www.lihaoyi.com/upickle/#Defaults

>  If a field at serialization time has the same value as the default, uPickle leaves it out of the serialized blob

**Comment by dandavison** [comment]
Hi @lihaoyi, thanks for this library. Might it make sense to have the ability to override this behavior?

I understand that the behavior is designed for evolving a schema. I think it's clear that it's useful to have the other behavior also but, just to be explicit -- when serializing a data structure for consumption by a different application one will sometimes simply want to serialize the data structure faithfully, regardless of whether or not the values match default values defined in the originating application. E.g. someone with a large sparsely-occupied case class might set the default to `None` or `""` on all the fields simply to reduce lines of code, i.e. using constructors that supply the non-empty fields only. But they'd still want the JSON to have all keys, empty-values or not.

**Comment by szymon-rd** [comment]
@lihaoyi Could this behavior be changed? I've heard reports of it affecting the DX negatively and I'm wondering what we can do with that.

**Comment by lihaoyi** [comment]
It's unlikely we can change it as the default due to compatibility, but it should be possible to make it configurable via a custom configuration, via flags, or via annotations

So far nobody has sent a PR to do so, but it can be done if anyone is sufficiently motivated, and in a binary/source compatible fashion
