### ISSUE TITLE
upickle-implicits pulls in an unnecessary utest runtime dependency

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/upickle#255]
It isn't used, probably just an accident

**Comment by pioorg** [comment]
Hello @lihaoyi 

I'm not sure in what sense you wrote "it isn't used".
In my setup it actually lands in the optimised JS file, adding ~300kB.

I'm trying to exclude it from the dependency tree without much luck so far.
Sadly, this makes upgrade from 0.6.7 to 0.7.x a no-go for us.
