### ISSUE TITLE
Unexpected result when parsing of too big integer or floating point numbers without dot as numeric primitives

### ISSUE THREAD

**Issue by plokhotnyuk** [lihaoyi/upickle#259]
```
scala> upickle.default.read[Byte]("999")
res0: Int = -25

scala> upickle.default.read[Byte]("0e0")
res1: Int = 18

scala> upickle.default.read[Short]("99999")
res2: Short = -31073

scala> upickle.default.read[Short]("0e0")
res3: Short = 530

scala> upickle.default.read[Char]("99999")
res4: Char = 蚟

scala> upickle.default.read[Char]("0e0")
res5: Char = Ȓ

scala> upickle.default.read[Int]("9999999999")
res6: Int = 1410065407

scala> upickle.default.read[Int]("0e0")
res7: Int = 530

scala> upickle.default.read[Long]("0e0")
res8: Long = 530
```

**Comment by raquo** [comment]
`read` assumes you give it a correct type param.

You can't rely on `read` throwing an exception if you give it an incorrect type param because in general it is impossible to make such a guarantee, as values of different types can be serialized into the same JSON.

**Comment by lihaoyi** [comment]
We can nevertheless be stricter than we are now throwing exceptions for out-of-bounds numbers, and the bad parsing of `0e0` notation is just a bug

**Comment by yarulan** [comment]
@raquo The type param is correct.

**Comment by lihaoyi** [comment]
Handling of exponents is fixed by https://github.com/lihaoyi/upickle/commit/1d4ae8e066292a14e4f958953228ef1ba31bd097, going to call integer overflow and wrap-around a wontfix since it matches what most bespoke handling of integer parsing is going to do anyway
