### ISSUE TITLE
ujson cannot set attribute to null

### ISSUE THREAD

**Issue by nemoo** [lihaoyi/upickle#265]
Currently it is possible to use ujson to conveniently mutate json like in this example: 

> val json = ujson.read(string)
> json("url") = "hello"

I actually want to mutate my json object to look like this:

> {url: null}

Still, I have not found a way to mutate a json value to null. So this does not work:

> json("url") = null

Neither does this work: 

> json("url") = None

Am I doing something wrong or is this a feature request?

**Comment by lihaoyi** [comment]
`ujson.Null`
