### ISSUE TITLE
Add null-safe helper functions with ujson.Value#{str,num,obj,arr,bool}

### ISSUE THREAD

**Issue by lihaoyi-databricks** [lihaoyi/upickle#266]
e.g. `.strOpt: Option[String]`, which would return `None` if the thing is `ujson.Null`

**Comment by nemoo** [comment]
Using upickle 0.8.0:
My expectation was document("xyz").strOpt would now return None if the key does not exist at all in the document. Instead it blows up on me with an Unexpected exception[NoSuchElementException: key not found: xyz

Currently I have to surround any key access that could go wrong with a try/catch, wouldn't it be nice if this case was also handled safely as an Option?

**Comment by lust4life** [comment]
@nemoo  maybe this `val newStartLine = document.obj.get("xyz").map(_.str)` will work around
.
