### ISSUE TITLE
How to get keys from Value

### ISSUE THREAD

**Issue by milnomada** [lihaoyi/upickle#271]
Hi,
I'm using your code and it works great for my scope.
I would like to ask you how would you proceed with the following:

When I use a Obj type I get the keys as follows:
```
val elem=Obj(
    "whatever"->"something",  
    "type"->"any"  
)
elem.value.map(a=>(a._1)).toList
```
How could I get the set of keys of the elem:Value?
```
val elem=ujson.read(r.text)
````
Thanks for any help.

**Comment by lihaoyi** [comment]
please ask questions on the gitter channel
