### ISSUE TITLE
Custom pickling for sealed hierarchies

### ISSUE THREAD

**Issue by kamilkloch** [lihaoyi/upickle#272]
Citing the manual, "sealed hierarchies are serialized as tagged values, the serialized object tagged with the full name of the instance's class". It works like this:
```scala
sealed trait A
case class B(x: Int) extends A
case class C(x: Boolean) extends A

implicit val aW: Writer[A] = Writer.merge(macroW[B], macroW[C])
println(write(s, 2))
```
```json
[
  {
    "$type": "Tests.B",
    "x": 1
  },
  {
    "$type": "Tests.C",
    "x": false
  }
]
```
Tagged attribute is not the most beautiful, moreover, the package name is hardcoded into Json, making it vulnerable to any refactoring. 

Is there an easy way to override the default picklers and achieve the following result?
```json
[
  {
    "B" : {
      "x" : 1
    }
  },
  {
    "C" : {
      "x" : false
    }
  }
]
```

Thanks!

**Comment by lihaoyi** [comment]
questions go in the gitter channel
