### ISSUE TITLE
Denial of service when parsing JSON object by uJson with keys that have the same hash code

### ISSUE THREAD

**Issue by plokhotnyuk** [lihaoyi/upickle#273]
_Sub-quadratic_ decreasing of throughput when number of JSON object fields (with keys that have the same hash code) is increasing

On contemporary CPUs parsing with uJson of such JSON object (with a sequence of 100000 fields like below that is ~1.6Mb) can took more than 100 seconds at ~4GHz:

```
{
"!!sjyehe":null,
"!!sjyeiF":null,
"!!sjyej'":null,
"!!sjyfIe":null,
"!!sjyfJF":null,
...
}
``` 

Below are results of the benchmark where `size` is a number of such fields:

```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                     (size)   Mode  Cnt        Score        Error  Units
[info] ExtractFieldsReading.uJson         1  thrpt    3  1487354.819 ±  83898.869  ops/s
[info] ExtractFieldsReading.uJson        10  thrpt    3   250920.609 ±  34064.565  ops/s
[info] ExtractFieldsReading.uJson       100  thrpt    3    13192.592 ±   4909.302  ops/s
[info] ExtractFieldsReading.uJson      1000  thrpt    3      325.361 ±     34.991  ops/s
[info] ExtractFieldsReading.uJson     10000  thrpt    3        2.133 ±      0.591  ops/s
[info] ExtractFieldsReading.uJson    100000  thrpt    3        0.009 ±      0.013  ops/s
[info] ExtractFieldsReading.uPickle       1  thrpt    3  1109304.645 ± 221248.420  ops/s
[info] ExtractFieldsReading.uPickle      10  thrpt    3   173577.038 ± 237304.899  ops/s
[info] ExtractFieldsReading.uPickle     100  thrpt    3    19666.200 ±  15157.982  ops/s
[info] ExtractFieldsReading.uPickle    1000  thrpt    3     2060.346 ±   1449.021  ops/s
[info] ExtractFieldsReading.uPickle   10000  thrpt    3      199.655 ±    134.897  ops/s
[info] ExtractFieldsReading.uPickle  100000  thrpt    3       20.726 ±      8.587  ops/s```
```

To run that benchmarks on your JDK:
1. [Install latest version of `sbt`](https://www.scala-sbt.org/1.0/docs/Setup.html) and/or ensure that it already installed properly: 
```
sbt about
```

2. Clone `jsoniter-scala` repo: 
```
git clone https://github.com/plokhotnyuk/jsoniter-scala.git
```

3. Enter to the cloned directory and checkout for the specific branch:
```
cd jsoniter-scala
git checkout json4s-DoS-by-hashmap-collisions
```

4. Run benchmarks using a path parameter to your JDK:
```
sbt 'jsoniter-scala-benchmark/jmh:run -wi 3 -i 3 ExtractFieldsReading.u'
```

**Comment by lihaoyi** [comment]
wontfix. Open a bug against scala/scala

**Comment by lihaoyi** [comment]
you can also parse into some other AST if you don’t like the builtin one. Serializing Scala data types doesn’t involve the AST at all, as your benchmarks have shown.

**Comment by plokhotnyuk** [comment]
@lihaoyi are you not happy from a feedback of those benchmarks? will you wait it from the users whose business happened to be affected?

**Comment by joshlemer** [comment]
@plokhotnyuk maybe you've mentioned elsewhere, but what do you suggest that ujson does to fix this issue, avoid using LinkedHashMap to represent json objects? Maybe the simplest/easiest fix would be to put together a private implementation of a `LinkedCollisionProofHashMap` which leverages a `scala.collection.mutable.CollisionProofHashMap[String, Node[String, JsValue]]` where `Node` is 

```scala
final class Node[K,V](var earlier: Node[K,V], val k: K, var v: V, var later: Node[K, V])
```

It should be pretty simple implement, I'd guess less than 100 lines. Much more ambitiously, a custom fork of CollisionProofHashMap could be made to be both Linked, and specialized to `K=String,V=JsValue` to avoid the double boxing (both CollisionProofHashMap Nodes and our own linking Nodes) as well as avoid caching the key hashcodes, since Strings already cache their hashcodes. But this version would be ~1000 lines (compare with the CollisionProofHashMap in stdlib).

**Comment by plokhotnyuk** [comment]
@joshlemer yeah, there are number of options and these, proposed by you are most safe and efficient.

Other low hanging fruits to fix `O(n^2)` complexity of the reported case could be using of wrapped `java.util.LinkedHashMap`, or just `Seq` of key/value pairs.

**Comment by Ichoran** [comment]
This issue really ought to be solved by the Scala library, or at least by some other compatible library.  It's kind of unreasonable to expect everyone who might have to deal with maliciously-crafted data to roll their own ideally-order-aware certainly-String-hash-collision-safe dictionary.  Doesn't _everyone_, not just uJson, have a problem with malicious key structures of this type?

**Comment by mdedetrich** [comment]
@Ichoran I guess you can say its a lot more prominent in the "world of JSON" land we live in.

**Comment by SethTisue** [comment]
> This issue really ought to be solved by the Scala library

Is there a scala/bug ticket on this? If so, please link to it; if not, I invite y'all to open one.

previously in this space: https://github.com/scala/scala/pull/7633
