### ISSUE TITLE
ujson-play_2.13 0.7.5 not released?

### ISSUE THREAD

**Issue by DWvanGeest** [lihaoyi/upickle#279]
Hi, thanks for this great lib!

It looks like `ujson-play_2.13` has not been released on maven.org, see https://search.maven.org/search?q=ujson-play_2.13. I note that 0.7.5 _was_ released for `2.13.0-M5`. Is there any reason the 2.13 version hasn't been updated? I note that Play 2.7 does support 2.13 final.

Thanks!

**Comment by lihaoyi** [comment]
Only reason is play json didnt support 2.13 back when upickle was upgraded.
It’s only one file though, so feel free to copy paste it into your own
project!

**Comment by DWvanGeest** [comment]
Ah, fair enough. Thanks for the tip.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/upickle/pull/282
