### ISSUE TITLE
Enhancement request: add Integer support to the AST 

### ISSUE THREAD

**Issue by hmf** [lihaoyi/upickle#308]
I have been having difficulty using ujson because I need to differentiate between floats and integers in order to support the Plotly.js Json schema correctly. For testing purposes  I use Json4s and noticed that it correctly handles this requirement. The [json4s AST](https://github.com/json4s/json4s#guide) makes this possible. 

Any way Num can be extended (split) into an Integer and Real?

TIA

**Comment by htmldoug** [comment]
Relevant:
- https://github.com/lihaoyi/upickle/issues/240#issuecomment-557545900
- https://github.com/lihaoyi/upickle/issues/240#issuecomment-557548375

**Comment by hmf** [comment]
@htmldoug Thanks for the links. 
I would include this https://github.com/lihaoyi/upickle/issues/240#issuecomment-414930124 also, seeing as it shows a possible solution.
