### ISSUE TITLE
Publishing version from Dotty community build?

### ISSUE THREAD

**Issue by mario-galic** [lihaoyi/upickle#309]
Dotty [community build](https://github.com/lampepfl/dotty/tree/master/community-build/community-projects/) lists [`upickle @ dd80d6b`](https://github.com/dotty-staging/upickle/tree/dd80d6bffa9e86de86602ee69a629c3984c153ca) as supported. I was wondering if the corresponding version could be published to Maven? Currently I cannot seem to find the relevant version at https://repo1.maven.org/maven2/com/lihaoyi/

**Comment by jodersky** [comment]
We're working on it.

**Comment by mario-galic** [comment]
There exists scala3 version at https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_3.0.0-M2/
