### ISSUE TITLE
Macro implicits don't work outside package

### ISSUE THREAD

**Issue by japgolly** [lihaoyi/upickle#31]
Hey. Check this out:
https://github.com/japgolly/upickle/commit/9a976af73ed46eeb7364829e457a973719ed9a7b

`Eg2` compiles but `Eg1` doesn't.

```
[error] upickle/jvm/shared/test/scala/upickle/blah/blah.scala:7: uPickle does not know how to read [upickle.elsewhere.YYY]s; define an implicit Reader[upickle.elsewhere.YYY] to teach it how
[error]   def blah(j: String): YYY = read[YYY](j)
[error]                                       ^
[warn] one warning found
[error] one error found
[error] upickle/js/shared/test/scala/upickle/blah/blah.scala:7: uPickle does not know how to read [upickle.elsewhere.YYY]s; define an implicit Reader[upickle.elsewhere.YYY] to teach it how
[error]   def blah(j: String): YYY = read[YYY](j)
[error]                                       ^
[warn] one warning found
[error] one error found
```

**Comment by tindzk** [comment]
After I made changes in some unrelated areas of my code, this issue suddenly showed up.

@l15k4 Could you give an example how inheriting from ``Implicits`` fixed the problem? It contains unimplemented functions, so how would that work?

I also defined an implicit in my ``Protocol`` class which is in a different package. Then, I evaluate this implicit where ``upickle.write()`` is called, but to no avail.

**Comment by l15k4** [comment]
@tindzk I can't figure out what I meant by "I default to either inheriting from Implicits trait". To my knowledge if you have custom R/W implicits in a different package than you need to directly `import` them to the scope where `upickle.write()` is called and it should work.

**Comment by tindzk** [comment]
There must be something in Widok that collides with upickle. When I comment out ``import org.widok._``, the errors vanish. My first idea was that this is related to the implicits that I define [here](https://github.com/widok/widok/blob/master/src/main/scala/org/widok.scala), but even if I import these manually, I cannot reproduce this issue. I wish scalac would provide a bit more guidance. So a temporary solution for now is to encapsulate any upickle-related code in a separate file and ensure that no conflicting imports are made.

**Comment by l15k4** [comment]
Guys this issue is still pretty nasty. I happened to remove an import statement of Reader & Writer evidence classes for pickling a custom datastructure, that Intellij idea considered unused when upgrading versions and later I spent 2 hours investigating why I'm getting really weird brand new scalac errors...Although I believe that recognizing this kind of problem must be pretty hard... Fingers crossed it won't happen again.

**Comment by l15k4** [comment]
I knew that this issue made it so risky to choose upickle for a project and yet I did it again and here I am, chasing this issue for 3 hours... Even though my code is entirely within a single package and I know about a few other tricks that usually solved it like proper ordering and avoiding nested classes... And still god damn : 
> The referenced trait [[Aggregation]] does not have any sub-classes. This may  happen due to a limitation of scalac (SI-7046) given that the trait is not in the same package. If this is the case, the hierarchy may be defined using integer constants.

**Comment by lihaoyi** [comment]
Moot with 0.5.1
