### ISSUE TITLE
empty collection serialization

### ISSUE THREAD

**Issue by toStars21** [lihaoyi/upickle#311]
how to reproduce:
create an empty sequence of strings

`  val arr = Seq.empty[String] `
`  val json = Obj("arr" -> Arr(arr.map(v => Str(v)))) `
` println(ujson.write(json)) `

Actual Output:
` {"arr":[[]]} `

Expected Output:
` {"arr":[]} `

**Comment by lihaoyi** [comment]
questions go in the gitter channel

**Comment by toStars21** [comment]
but as for me it looks like deffect, not a question
