### ISSUE TITLE
Obtaining parse tree

### ISSUE THREAD

**Issue by tindzk** [lihaoyi/upickle#56]
The following fails with an expansion error:

```scala
upickle.read[Js.Arr](contents)
```

I came up with a quick workaround, but I'd prefer if the above line worked:

```scala
case class Tree(tree: Js.Arr)
implicit val treeReader = upickle.Reader[Tree] {
  case t: Js.Arr => Tree(t)
}

upickle.read[Tree](contents)
```

**Comment by lihaoyi** [comment]
If you are wanting to read in `Js.*` blobs in particular, upickle.json `readJs` function should let you do that. or `upickle.json.read`/`upickle.json.readJs`.

Of course, if you want to parse it using upickle's default pickling, that's another matter. I haven't tested it, but I bet we could make it work

**Comment by tindzk** [comment]
I should have been more clear. The input is a JSON string and I expect ``upickle.read[Js.Arr](json)`` to return the full parse tree as-is, i.e. no pickling implicits should be applied. The above works, but I have to declare a case class and an implicit.

**Comment by lihaoyi** [comment]
Yeah and `upickle.json.read` does exactly that
