### ISSUE TITLE
Case objects unsupported

### ISSUE THREAD

**Issue by tindzk** [lihaoyi/upickle#57]
uPickle cannot deal with case objects as shown in the following code:

```scala
trait Type
object Type {
  case object A extends Type
  case object B extends Type
}

upickle.read[Type]("") // Error: uPickle does not know how to read [Type]s; define an implicit Reader[Type] to teach it how
```

Edit: When the trait is ``sealed``, the above compiles without problems. Could the macro issue an error in such cases?

**Comment by lihaoyi** [comment]
Needs to be sealed. Yeah, it should report a better error message. In general, error reporting could use a lot of work =/ Let's leave this open until we fix it

**Comment by lihaoyi** [comment]
Closed by https://github.com/lihaoyi/upickle/pull/58, thanks!
