### ISSUE TITLE
Customizable discrimination annotations

### ISSUE THREAD

**Issue by netvl** [lihaoyi/upickle#64]
It would be nice if annotation format could be customized, for example, in order to have 
```
{ "$variant": "MyClass", "key": "value" }
````
instead of 
```
["your.package.MyClass", {"key": "value"}]
```

While such approach can lead to collisions, with some fancy discriminator key it will be very unlikely (and it is not really a problem if it can be configured). It would also be nice to be able to store only the last part of the discriminator value (or, for example, two parts if `MyClass` is defined in an `object`).

As far as I can see (I may be wrong, though) it should not be very difficult - currently the autogenerated picklers depend on `Internal.annotate` behavior; I think it should be possible to extract the annotation behavior to another implicit and provide the default one with the current behavior.

Having the discriminator as a part of the object is important (at least for our project) for migration reasons (a lot of other serializators are using this format) and for working with the serialized objects - for example, mongodb queries tend to be simpler without arrays.

**Comment by lihaoyi** [comment]
Yeah, I want to do this too. It'd make interoperating with other json
producers/consumers much easier since afaict nobody else does my
tagged-union-as-array thing

**Comment by lihaoyi** [comment]
Closing in preference for https://github.com/lihaoyi/upickle/issues/55
