### ISSUE TITLE
Republish for scalajs-0.6.1

### ISSUE THREAD

**Issue by ramnivas** [lihaoyi/upickle#72]
To ensure that uPickle users benefit from https://github.com/scala-js/scala-js/issues/1506 (and avoid symptoms seen in https://github.com/scala-js/scala-js/issues/1514), uPickle needs to be republished for scalajs-0.6.1.

**Comment by ddispaltro** [comment]
Do you need to recompile to fix the problem or is it just a dependency
thing?


-Dan

**Comment by ramnivas** [comment]
I believe the following patch needs to be applied (bumped product `version` too, since I am not sure republishing a published artifact is allowed or even a good idea). BUT... when I tried to `sbt publishLocal`, I got unresolved `com.lihaoyi#utest_sjs0.6_2.10;0.2.5`, thus not making a PR off of it.

```
diff --git a/build.sbt b/build.sbt
index 6d534a1..70d7658 100644
--- a/build.sbt
+++ b/build.sbt
@@ -2,7 +2,7 @@ crossScalaVersions := Seq("2.10.4", "2.11.4")
 
 val upickle = crossProject.settings(
   organization := "com.lihaoyi",
-  version := "0.2.6",
+  version := "0.2.7",
   scalaVersion := "2.10.4",
   name := "upickle",
   scalacOptions := Seq("-unchecked",
diff --git a/project/build.sbt b/project/build.sbt
index 40a67d6..0dd657b 100644
--- a/project/build.sbt
+++ b/project/build.sbt
@@ -1 +1 @@
-addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.0")
+addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.1")
```

**Comment by lihaoyi** [comment]
I'm also not clear. @sjrd does this mean the generated IR changed with that fix?

**Comment by sjrd** [comment]
Yes the generated IR changed. It's still *compatible*, though, in the sense that the linker of 0.6.0 can read .sjsir files produced by 0.6.1 and vice versa. Basically the output of the 0.6.0 compiler was buggy. So yes a recompilation is needed. It is not just a dependency thing, otherwise I would not have told you in the first place.

**Comment by lihaoyi** [comment]
Ok cool, I'll give everything a recompile next pass

**Comment by lihaoyi** [comment]
This has happened
