### ISSUE TITLE
Cannot create Js.Arr from a Seq[Js.Value]

### ISSUE THREAD

**Issue by rabejens** [lihaoyi/upickle#84]
To reproduce:

```scala
val arr = Js.Arr(Seq(Js.Str("a"), Js.Str("b")))
```

Expected: an `Arr` is created
Actual: Compiler error:
```
[error]  found   : Seq[upickle.Js.Str]
[error]  required: upickle.Js.Value
[error]     val arr = Js.Arr(Seq(Js.Str("a"), Js.Str("b")))
[error]                         ^
```

This happens when using Scala.js and compiling in the set console with `compile`

`Js.Arr` has a varargs `apply` and Scala should auto-convert varargs to `Seq`, but it incorrectly uses the other `apply` method.

**Comment by lihaoyi** [comment]
Try `Js.Arr(Seq(Js.Str("a"), Js.Str("b")):_*)`?
